sudo: required

services:
  - docker

language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - script/setup

script:
  - docker-compose up -d web
  # The script is simple, 30s should be enough.
  - timeout 30s script/ci
