sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.6.0

before_install:
  - script/setup

script:
  - docker-compose up -d web
  # The script is simple, 30s should be enough.
  - timeout 30s script/ci
